Fix clang 21 warnings (#83499)
* Fix clang 21 warnings

Due to
error: function 'operator()' could be declared with attribute 'noreturn' [-Werror,-Wmissing-noreturn]

ref:
https://github.com/llvm/llvm-project/issues/154493

* Move another compiler macro to cata_compiler_support.h

* Fix conditional define for all compilers