Fix GCC9 unused variable method.
Fixes "src/mapgen_functions.cpp:2827:16: error: variable ‘unify_all_borders’ set but not used [-Werror=unused-but-set-variable]". Norably, this also corresponded to a logic error, and subsequent genrations following this fix will be nicer in the case of figure 5.