Makefile: add -fwrapv to flags to eliminate stupid -Wstrict-overflow errors
Encountered this compile error on -O3 (without LTO):

    src/iexamine.cpp: In function ‘void iexamine::fswitch(player&, const tripoint&)’:
    src/iexamine.cpp:1195:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
     void iexamine::fswitch(player &p, const tripoint &examp)
	  ^
    cc1plus: all warnings being treated as errors

I wasn't clear on what it was actually *looking* at, because the line number
was so completely helpful, and used creduce to figure out what the problem was:

    int iexaminegaspump_y {
	iexaminegaspump_y <= iexaminegaspump_y + 5

So it appears this conditional in the for loop was triggering it:

    for (y = examp.y; y <= examp.y + 5; y++ ) {

This is a case where the compiler is taking liberties it really shouldn't, in
the name of optimization:

    [C++11:N3242$5.0.4]
    If during the evaluation of an expression, the result is not mathematically
    defined or not in the range of representable values for its type, the behavior
    is undefined.

The GCC writers took that "undefined" to mean "oh, well, we can assume it never
overflows!" Which is insane. If you try to add (INT_MAX + 1), you're going to
get INT_MIN. That's just how the hardware works.

The -fwrapv option adds some much-needed sanity:

    This option instructs the compiler to assume that signed arithmetic
    overflow of addition, subtraction and multiplication wraps around using
    twos-complement representation.

Signed-off-by: Steven Noonan <steven@uplinklabs.net>