worldfactory: fix one-definition rule violation with 'tabs' vector
Discovered with LTO:

    src/worldfactory.h:89:77: error: type ‘struct worldgen_display’ violates one definition rule [-Werror=odr]
	     typedef int ( worldfactory::*worldgen_display )( WINDOW *, WORLDPTR );
										 ^
    /usr/include/c++/5.3.0/bits/allocator.h:101:19: note: a different type is defined in another translation unit
	   typedef _Tp        value_type;
		       ^
    src/worldfactory.h:89:77: note: the first difference of corresponding definitions is field ‘__pfn’
	     typedef int ( worldfactory::*worldgen_display )( WINDOW *, WORLDPTR );
										 ^
    src/worldfactory.h:89:77: note: a field of same name but different type is defined in another translation unit
    lto1: note: type mismatch in parameter 3
    lto1: all warnings being treated as errors

Note that "different type" shows up in std::allocator. The simplest solution
I've found is to turn worldfactory::tabs into a vector of std::functions
instead of a vector of C-style function pointers.

Signed-off-by: Steven Noonan <steven@uplinklabs.net>