Allow operand number formats on g++14
My compiler (`g++ (Debian 14.2.0-1) 14.2.0`) gives this error when
compiling:
```
src/magic.cpp: In member function ‘void spellcasting_callback::display_spell_info(size_t)’:
src/magic.cpp:2624:24: error: ISO C++11 does not support %n$ operand number formats [-Werror=format=]
 2624 |             ImGui::Text( _( "Spawn item group %1$s %2$d times" ),
      |             ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 2625 |                          sp.effect_data().c_str(),
      |                          ~~~~~~~~~~~~~~~~~~~~~~~~~
 2626 |                          sp.damage( pc ) );
      |                          ~~~~~~~~~~~~~~~~~
```

Compiler flags used:
```
CCACHE_SLOPPINESS=pch_defines,time_macros,include_file_ctime,include_file_mtime ccache g++ -Isrc -isystem src/third-party -DRELEASE -DGIT_VERSION -DTILES -DUSE_HOME_DIR -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -D_GLIBCXX_ASSERTIONS -fstrict-flex-arrays=3 -fstack-clash-protection -fstack-protector-strong -Wl,-z,nodlopen -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Os -Wodr -Werror -Wall -Wextra -Wformat-signedness -Wlogical-op -Wmissing-declarations -Wmissing-noreturn -Wnon-virtual-dtor -Wold-style-cast -Woverloaded-virtual -Wpedantic -Wsuggest-override -Wunused-macros -Wzero-as-null-pointer-constant -Wno-unknown-warning-option -Wno-dangling-reference -Wno-c++20-compat -Wredundant-decls -g -fsigned-char -std=c++17 -I/usr/include/SDL2 -D_REENTRANT -I/usr/include/SDL2 -I/usr/include/libpng16 -I/usr/include/x86_64-linux-gnu -I/usr/include/webp -D_REENTRANT -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sysprof-6 -pthread -MMD -MP -Winvalid-pch -include pch/main-pch.hpp -c src/magic.cpp -o obj/tiles/magic.o
```