Fix clang 21 warnings
Due to
error: function 'operator()' could be declared with attribute 'noreturn' [-Werror,-Wmissing-noreturn]

ref:
https://github.com/llvm/llvm-project/issues/154493